/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useSpring, animated } from "@react-spring/three";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { monitor } from "leva";

export function Room(props) {
  const { nodes, materials } = useGLTF("models/roomoptimized1-v1.glb");

  let value = props.seatVisible;
  let monitorRef = useRef();
  let doorRef = useRef();
  let isOpen = props.isOpen;
  let seatRotating = props.seatRotating;
  let seatRef = useRef();
  let seatRotationRef = props.seatRotationRef; // Ref to store seat rotation

  // Door Rotation Animation
  const { rotation } = useSpring({
    rotation: isOpen ? [0, -Math.PI / 2, 0] : [0, 0, 0], // Rotates -90° on Y-axis
    config: { mass: 1, tension: 170, friction: 26 },
  });


  // Chair Rotation Animation
  const rotation1  = useSpring({
    rotation: seatRotating ? [0, -Math.PI, 0] : [0, 0.013, 0], // Rotates -90° on Y-axis
    config: { mass: 1, tension: 170, friction: 26 },
    onRest: () => console.log("Rotation complete"),
    onChange: ({ value }) => {
      if (seatRotationRef) seatRotationRef.current = value; // Update the ref
    },
  });

  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.021, 1.151, -1.036]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[0.032, 0.035, 0.065]}
        name="mouse"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164_1.geometry}
          material={materials.Bootom}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane164_2.geometry}
          material={materials.Center}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitor_stand.geometry}
        material={nodes.monitor_stand.material}
        position={[-1.586, 1.219, -0.676]}
        scale={0.858}
      />
      <group
        position={[-1.739, 1.271, -0.016]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.034, 1, 0.951]}
        name="cpu"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane198_1.geometry}
          material={materials["Metalic.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane198_2.geometry}
          material={materials.Gagang}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane198_3.geometry}
          material={materials["png-apple-logo-9711"]}
        />
      </group>
      <group
        position={[-1.609, 1.356, -0.683]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.07}
        name="monitor"
        ref={monitorRef}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["png-apple-logo-9711001"].geometry}
          material={materials["png-apple-logo-9711"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["png-apple-logo-9711001_1"].geometry}
          material={materials.Metalic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["png-apple-logo-9711001_2"].geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["png-apple-logo-9711001_3"].geometry}
          material={materials["Screen.001"]}
        />
      </group>
      <group
        position={[-0.91, 0.914, -1.504]}
        scale={[1, 1.043, 1]}
        name="table"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane166.geometry}
          material={materials["White Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane166_1.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelf_frame.geometry}
        material={materials["Wood.002"]}
        position={[-1.736, 1.394, -1.542]}
        scale={0.635}
        name="shelf wood"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={nodes.Cylinder005.material}
          position={[-0.235, 0.029, 0.42]}
          scale={[1.037, 0.824, 1.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={nodes.Cylinder006.material}
          position={[-0.235, -0.305, 0.42]}
          scale={[1.037, 0.824, 1.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={nodes.Cylinder008.material}
          position={[-0.228, 0.002, 0.42]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.005}
          name="tires"
        />
      </mesh>
      <group
        position={[-1.145, 1.146, -0.722]}
        scale={[1, 1, 0.882]}
        name="mouse pad"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane195.geometry}
          material={materials.Mousepad}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane195_1.geometry}
          material={materials.mousepad}
        />
      </group>
      <group
        position={[-1.831, 1.405, -1.342]}
        rotation={[0, 0.175, 0]}
        scale={0.782}
        name="pen holder purple"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030.geometry}
          material={materials["Jar 2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030_1.geometry}
          material={materials.Scis}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030_2.geometry}
          material={materials["Brush.001"]}
        />
      </group>
      <group
        position={[-1.828, 1.403, -1.482]}
        rotation={[0.149, -0.941, 0.12]}
        scale={[1.2, 1, 1.2]}
        name="pen holder"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070.geometry}
          material={materials.Pencil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070_1.geometry}
          material={materials["Pencil.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070_2.geometry}
          material={materials["Jar.001"]}
        />
      </group>
      <group
        position={[-1.738, 1.259, -1.661]}
        rotation={[0, 0.165, 0]}
        scale={[0.864, 0.524, 0.864]}
        name="book"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube103.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube103_1.geometry}
          material={materials.Base}
        />
      </group>
      <group
        position={[-1.644, 1.483, -1.411]}
        rotation={[-0.82, 0.05, -1.517]}
        scale={[0.002, 0.002, 0.01]}
        name="pen"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane208.geometry}
          material={materials.Clock}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane208_1.geometry}
          material={materials["Eye-White"]}
        />
      </group>
      <group
        position={[-1.716, 1.227, -1.39]}
        scale={[0.118, 0.118, 0.095]}
        name="calculator"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209.geometry}
          material={materials.Kalkulator}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_3.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_4.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane209_5.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[-1.689, 1.397, -1.675]} scale={0.744} name="flower pot">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038_1.geometry}
          material={materials["Material.023"]}
        />
      </group>
      <group
        position={[-1.027, 1.151, -0.674]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.083}
        name="keyboard"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials["mac mini.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials.Button}
        />
      </group>
      {value && (
        <group name="seat">
          <animated.group
            position={[-0.48, 0.397, -0.59]}
            rotation={rotation1.rotation}
            scale={-0.026}
            name="chair upper"
            ref={seatRef}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_1.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_2.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_3.geometry}
              material={materials["Chair Pullow"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_4.geometry}
              material={materials["Plastic.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_5.geometry}
              material={materials.Trans}
            />
          </animated.group>
          <group
            position={[-0.478, 0.43, -0.587]}
            rotation={[0, 0.013, 0]}
            scale={0.961}
            name="seat floor"
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder012.geometry}
              material={materials.Ban}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder012_1.geometry}
              material={materials.Plastic}
            />
          </group>
        </group>
      )}
      <group
        position={[-1.535, 0.77, 0.825]}
        rotation={[0, 0, -0.712]}
        scale={[0.25, 0.174, 0.362]}
        name="bed"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130.geometry}
          material={materials["Piloow.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130_1.geometry}
          material={materials["Bed wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130_3.geometry}
          material={materials.Sprei}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130_4.geometry}
          material={materials.Pillow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane130_5.geometry}
          material={materials.Base}
        />
      </group>
      <group
        position={[-1.897, 2.451, -0.226]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.949}
        name="blue img"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane218.geometry}
          material={materials.Framee}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane218_1.geometry}
          material={materials.image}
        />
      </group>
      <group
        position={[-1.897, 2.451, -0.918]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.001, 0.949, 0.427]}
        name="my pic"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane220.geometry}
          material={materials.Framee}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane220_1.geometry}
          material={materials["image.001"]}
        />
      </group>
      <group
        position={[-1.871, 2.312, 1.138]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.498, 1, 0.614]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane221.geometry}
          material={materials.Fraa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane221_1.geometry}
          material={materials.imgg}
        />
      </group>
      <group
        position={[-0.374, 1.946, -1.946]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 0.866]}
        name="window blind"
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane100.geometry}
          material={materials["Base.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane100_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[0, 0.197, 0]} name="wall">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_1.geometry}
          material={materials.Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_2.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_3.geometry}
          material={materials["Floor.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane161_4.geometry}
          material={materials["Wall.001"]}
        />
      </group>
      <animated.group
        position={[1.297, 1.411, -1.849]}
        scale={0.998}
        name="door"
        ref={doorRef}
        rotation={rotation}
      >
        {/* <group position={[-0.5, 0, 0]}> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Base.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Metalic.002"]}
        />
        {/* </group> */}
      </animated.group>
    </group>
  );
}

useGLTF.preload("models/roomoptimized1-v1.glb");
